#!/bin/bash
# =============================================================================
# MASTER SECURITY HARDENING SCRIPT
# =============================================================================
# Description: Runs all security hardening scripts in correct order
# Usage: sudo bash security-full-setup.sh
# Author: DevOps Team
# Version: 1.0
# =============================================================================

set -euo pipefail

# -----------------------------------------------------------------------------
# CONFIGURATION
# -----------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_FILE="/var/log/security-setup-$(date +%Y%m%d-%H%M%S).log"
ADMIN_EMAIL="${1:-admin@localhost}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# -----------------------------------------------------------------------------
# FUNCTIONS
# -----------------------------------------------------------------------------
log() {
    echo -e "${GREEN}[$(date '+%Y-%m-%d %H:%M:%S')]${NC} $1" | tee -a "$LOG_FILE"
}

warn() {
    echo -e "${YELLOW}[WARNING]${NC} $1" | tee -a "$LOG_FILE"
}

error() {
    echo -e "${RED}[ERROR]${NC} $1" | tee -a "$LOG_FILE"
}

header() {
    echo "" | tee -a "$LOG_FILE"
    echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}" | tee -a "$LOG_FILE"
    echo -e "${BLUE} $1${NC}" | tee -a "$LOG_FILE"
    echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}" | tee -a "$LOG_FILE"
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        error "This script must be run as root (use sudo)"
        exit 1
    fi
}

# -----------------------------------------------------------------------------
# PRE-FLIGHT CHECKS
# -----------------------------------------------------------------------------
check_root

header "🔒 SECURITY HARDENING - STARTING"
log "Log file: $LOG_FILE"
log "Admin email: $ADMIN_EMAIL"

# Backup current configs
BACKUP_DIR="/root/security-backup-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$BACKUP_DIR"
log "Backup directory: $BACKUP_DIR"

# Backup important files
cp /etc/ssh/sshd_config "$BACKUP_DIR/" 2>/dev/null || true
cp /etc/sysctl.conf "$BACKUP_DIR/" 2>/dev/null || true
log "Existing configurations backed up"

# -----------------------------------------------------------------------------
# STAGE 1: SYSTEM UPDATES
# -----------------------------------------------------------------------------
header "📦 STAGE 1: System Updates"

log "Updating package lists..."
apt-get update -qq

log "Upgrading installed packages..."
DEBIAN_FRONTEND=noninteractive apt-get upgrade -y -qq

log "Installing essential security packages..."
apt-get install -y -qq \
    ufw \
    fail2ban \
    unattended-upgrades \
    apt-listchanges \
    auditd \
    audispd-plugins \
    aide \
    rkhunter \
    chkrootkit \
    logwatch \
    acct \
    sysstat \
    net-tools \
    curl \
    wget \
    gnupg2

log "✅ System updates completed"

# -----------------------------------------------------------------------------
# STAGE 2: SSH HARDENING
# -----------------------------------------------------------------------------
header "🔑 STAGE 2: SSH Hardening"

# Run SSH hardening script
if [[ -f "$SCRIPT_DIR/security/harden-ssh.sh" ]]; then
    bash "$SCRIPT_DIR/security/harden-ssh.sh"
else
    log "Running inline SSH hardening..."
    
    # Backup original sshd_config
    cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup
    
    # Apply secure SSH configuration
    cat > /etc/ssh/sshd_config << 'SSHEOF'
# =============================================================================
# SECURE SSH CONFIGURATION
# =============================================================================
# Generated by security-full-setup.sh
# Last updated: $(date)
# =============================================================================

# -----------------------------------------------------------------------------
# NETWORK
# -----------------------------------------------------------------------------
Port 22
AddressFamily inet
ListenAddress 0.0.0.0

# -----------------------------------------------------------------------------
# AUTHENTICATION
# -----------------------------------------------------------------------------
PermitRootLogin no
PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
UsePAM yes

# -----------------------------------------------------------------------------
# SECURITY
# -----------------------------------------------------------------------------
X11Forwarding no
AllowTcpForwarding no
AllowAgentForwarding no
PermitTunnel no
MaxAuthTries 3
MaxSessions 3
ClientAliveInterval 300
ClientAliveCountMax 2
LoginGraceTime 30

# -----------------------------------------------------------------------------
# LOGGING
# -----------------------------------------------------------------------------
SyslogFacility AUTH
LogLevel VERBOSE

# -----------------------------------------------------------------------------
# ALLOWED USERS (Uncomment and modify as needed)
# -----------------------------------------------------------------------------
# AllowUsers ubuntu admin deploy
# AllowGroups sudo admin

# -----------------------------------------------------------------------------
# CRYPTOGRAPHY (Strong algorithms only)
# -----------------------------------------------------------------------------
KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com

# -----------------------------------------------------------------------------
# BANNER
# -----------------------------------------------------------------------------
Banner /etc/ssh/banner
PrintMotd no
PrintLastLog yes

# -----------------------------------------------------------------------------
# SFTP
# -----------------------------------------------------------------------------
Subsystem sftp /usr/lib/openssh/sftp-server -f AUTHPRIV -l INFO
SSHEOF

    # Create SSH banner
    cat > /etc/ssh/banner << 'BANNEREOF'
═══════════════════════════════════════════════════════════════════════════════
                         AUTHORIZED ACCESS ONLY
═══════════════════════════════════════════════════════════════════════════════
This system is for authorized users only. All activities are monitored and
logged.  Unauthorized access attempts will be reported to law enforcement.
By proceeding, you consent to monitoring and accept all terms of use.
═══════════════════════════════════════════════════════════════════════════════
BANNEREOF

    # Test SSH configuration
    if sshd -t; then
        log "SSH configuration valid, restarting service..."
        systemctl restart sshd
        log "✅ SSH hardening completed"
    else
        error "SSH configuration invalid, restoring backup..."
        cp /etc/ssh/sshd_config.backup /etc/ssh/sshd_config
        exit 1
    fi
fi

# -----------------------------------------------------------------------------
# STAGE 3: FIREWALL CONFIGURATION
# -----------------------------------------------------------------------------
header "🔥 STAGE 3: Firewall Configuration"

log "Configuring UFW firewall..."

# Reset UFW
ufw --force reset

# Default policies
ufw default deny incoming
ufw default allow outgoing

# Allow essential ports
ufw allow 22/tcp comment 'SSH'
ufw allow 80/tcp comment 'HTTP'
ufw allow 443/tcp comment 'HTTPS'

# Application ports (customize as needed)
ufw allow 3000/tcp comment 'Frontend App'
ufw allow 4000/tcp comment 'Backend API'

# Rate limiting for SSH
ufw limit ssh/tcp comment 'SSH Rate Limit'

# Enable UFW
ufw --force enable

log "✅ Firewall configured"
ufw status verbose | tee -a "$LOG_FILE"

# -----------------------------------------------------------------------------
# STAGE 4: FAIL2BAN SETUP
# -----------------------------------------------------------------------------
header "🚫 STAGE 4: Fail2Ban Configuration"

log "Configuring Fail2Ban..."

# Create Fail2Ban jail configuration
cat > /etc/fail2ban/jail.local << 'FAIL2BANEOF'
# =============================================================================
# FAIL2BAN JAIL CONFIGURATION
# =============================================================================

[DEFAULT]
# -----------------------------------------------------------------------------
# GENERAL SETTINGS
# -----------------------------------------------------------------------------
bantime = 3600
findtime = 600
maxretry = 5
backend = systemd
banaction = ufw

# -----------------------------------------------------------------------------
# EMAIL NOTIFICATIONS (Optional)
# -----------------------------------------------------------------------------
# destemail = admin@yourdomain.com
# sender = fail2ban@yourdomain.com
# mta = sendmail
# action = %(action_mwl)s

# =============================================================================
# JAILS
# =============================================================================

# -----------------------------------------------------------------------------
# SSH JAIL
# -----------------------------------------------------------------------------
[sshd]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 86400
findtime = 600

# -----------------------------------------------------------------------------
# SSH DDOS PROTECTION
# -----------------------------------------------------------------------------
[sshd-ddos]
enabled = true
port = ssh
filter = sshd-ddos
logpath = /var/log/auth.log
maxretry = 6
bantime = 172800
findtime = 600

# -----------------------------------------------------------------------------
# NGINX JAILS
# -----------------------------------------------------------------------------
[nginx-http-auth]
enabled = true
filter = nginx-http-auth
port = http,https
logpath = /var/log/nginx/error.log
maxretry = 3
bantime = 3600

[nginx-limit-req]
enabled = true
filter = nginx-limit-req
port = http,https
logpath = /var/log/nginx/error.log
maxretry = 10
bantime = 7200

[nginx-botsearch]
enabled = true
filter = nginx-botsearch
port = http,https
logpath = /var/log/nginx/access.log
maxretry = 2
bantime = 86400

# -----------------------------------------------------------------------------
# BAD BOTS
# -----------------------------------------------------------------------------
[nginx-badbots]
enabled = true
port = http,https
filter = nginx-badbots
logpath = /var/log/nginx/access.log
maxretry = 2
bantime = 86400

# -----------------------------------------------------------------------------
# REPEATED OFFENDERS
# -----------------------------------------------------------------------------
[recidive]
enabled = true
logpath = /var/log/fail2ban.log
banaction = ufw
bantime = 604800
findtime = 86400
maxretry = 3
FAIL2BANEOF

# Create custom Nginx filter for bad bots
mkdir -p /etc/fail2ban/filter.d
cat > /etc/fail2ban/filter.d/nginx-badbots.conf << 'BOTFILTEREOF'
# Fail2Ban filter for bad bots
[Definition]
failregex = ^<HOST> -.*"(GET|POST|HEAD).*HTTP.*" . * "(.*)(bot|crawler|spider|scraper|scanner).*"$
            ^<HOST> -.*"(GET|POST|HEAD).*(wp-login|xmlrpc|\. env|\.git|phpmyadmin|admin).*"$
ignoreregex =
BOTFILTEREOF

# Restart Fail2Ban
systemctl enable fail2ban
systemctl restart fail2ban

log "✅ Fail2Ban configured"
fail2ban-client status | tee -a "$LOG_FILE"

# -----------------------------------------------------------------------------
# STAGE 5: AUTOMATIC SECURITY UPDATES
# -----------------------------------------------------------------------------
header "🔄 STAGE 5: Automatic Security Updates"

log "Configuring unattended upgrades..."

cat > /etc/apt/apt.conf.d/50unattended-upgrades << 'UNATTENDEDEOF'
// =============================================================================
// UNATTENDED UPGRADES CONFIGURATION
// =============================================================================

Unattended-Upgrade:: Allowed-Origins {
    "${distro_id}:${distro_codename}";
    "${distro_id}:${distro_codename}-security";
    "${distro_id}ESMApps:${distro_codename}-apps-security";
    "${distro_id}ESM:${distro_codename}-infra-security";
};

// Auto-remove unused dependencies
Unattended-Upgrade::Remove-Unused-Dependencies "true";
Unattended-Upgrade:: Remove-Unused-Kernel-Packages "true";

// Auto-reboot if required (at 3 AM)
Unattended-Upgrade::Automatic-Reboot "true";
Unattended-Upgrade::Automatic-Reboot-Time "03:00";

// Email notifications
// Unattended-Upgrade::Mail "admin@yourdomain.com";
// Unattended-Upgrade:: MailReport "on-change";

// Logging
Unattended-Upgrade::SyslogEnable "true";
Unattended-Upgrade::SyslogFacility "daemon";
UNATTENDEDEOF

cat > /etc/apt/apt. conf.d/20auto-upgrades << 'AUTOEOF'
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Download-Upgradeable-Packages "1";
APT::Periodic::AutocleanInterval "7";
APT::Periodic::Unattended-Upgrade "1";
AUTOEOF

systemctl enable unattended-upgrades
systemctl restart unattended-upgrades

log "✅ Automatic updates configured"

# -----------------------------------------------------------------------------
# STAGE 6: KERNEL HARDENING
# -----------------------------------------------------------------------------
header "🛡️ STAGE 6: Kernel Hardening"

log "Applying kernel security parameters..."

cat > /etc/sysctl.d/99-security.conf << 'SYSCTLEOF'
# =============================================================================
# KERNEL SECURITY HARDENING
# =============================================================================

# -----------------------------------------------------------------------------
# NETWORK SECURITY
# -----------------------------------------------------------------------------
# Disable IP forwarding (unless this is a router)
net.ipv4.ip_forward = 0
net.ipv6.conf. =all.forwarding = 0

# Disable source routing
net.ipv4.conf.all.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0

# Disable ICMP redirects
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0

# Enable SYN flood protection
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 2048
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 5

# Ignore ICMP broadcasts
net.ipv4.icmp_echo_ignore_broadcasts = 1

# Ignore bogus ICMP errors
net.ipv4.icmp_ignore_bogus_error_responses = 1

# Enable reverse path filtering
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Log suspicious packets
net.ipv4.conf.all.log_martians = 1
net.ipv4.conf.default.log_martians = 1

# Disable IPv6 if not needed (uncomment if not using IPv6)
# net.ipv6.conf.all.disable_ipv6 = 1
# net.ipv6.conf.default.disable_ipv6 = 1

# -----------------------------------------------------------------------------
# MEMORY PROTECTION
# -----------------------------------------------------------------------------
# Restrict core dumps
fs.suid_dumpable = 0

# Randomize memory addresses (ASLR)
kernel.randomize_va_space = 2

# Restrict kernel pointer exposure
kernel.kptr_restrict = 2

# Restrict dmesg access
kernel.dmesg_restrict = 1

# Restrict perf events
kernel.perf_event_paranoid = 3

# -----------------------------------------------------------------------------
# FILE SYSTEM SECURITY
# -----------------------------------------------------------------------------
# Restrict access to kernel logs
kernel.printk = 3 4 1 3

# Protect hardlinks and symlinks
fs.protected_hardlinks = 1
fs.protected_symlinks = 1

# Restrict ptrace scope
kernel.yama.ptrace_scope = 1
SYSCTLEOF

# Apply sysctl settings
sysctl -p /etc/sysctl.d/99-security.conf

log "✅ Kernel hardening applied"

# -----------------------------------------------------------------------------
# STAGE 7: AUDIT LOGGING
# -----------------------------------------------------------------------------
header "📝 STAGE 7: Audit Logging"

log "Configuring audit logging..."

# Enable and configure auditd
cat > /etc/audit/rules.d/audit.rules << 'AUDITEOF'
# =============================================================================
# AUDIT RULES - CIS BENCHMARK COMPLIANT
# =============================================================================

# Delete all existing rules
-D

# Buffer size
-b 8192

# Failure mode (1=printk, 2=panic)
-f 1

# -----------------------------------------------------------------------------
# SYSTEM EVENTS
# -----------------------------------------------------------------------------
# Monitor system time changes
-a always,exit -F arch=b64 -S adjtimex -S settimeofday -k time-change
-a always,exit -F arch=b64 -S clock_settime -k time-change
-w /etc/localtime -p wa -k time-change

# Monitor user/group changes
-w /etc/group -p wa -k identity
-w /etc/passwd -p wa -k identity
-w /etc/gshadow -p wa -k identity
-w /etc/shadow -p wa -k identity
-w /etc/security/opasswd -p wa -k identity

# Monitor network configuration
-w /etc/hosts -p wa -k system-network
-w /etc/network/ -p wa -k system-network

# -----------------------------------------------------------------------------
# ACCESS CONTROL
# -----------------------------------------------------------------------------
# Monitor permission changes
-a always,exit -F arch=b64 -S chmod -S fchmod -S fchmodat -F auid>=1000 -F auid!=4294967295 -k perm_mod
-a always,exit -F arch=b64 -S chown -S fchown -S fchownat -S lchown -F auid>=1000 -F auid!=4294967295 -k perm_mod

# Monitor sudo usage
-w /etc/sudoers -p wa -k sudoers
-w /etc/sudoers. d/ -p wa -k sudoers

# -----------------------------------------------------------------------------
# AUTHENTICATION EVENTS
# -----------------------------------------------------------------------------
# Monitor login events
-w /var/log/faillog -p wa -k logins
-w /var/log/lastlog -p wa -k logins
-w /var/log/tallylog -p wa -k logins
-w /var/run/utmp -p wa -k session
-w /var/log/wtmp -p wa -k logins
-w /var/log/btmp -p wa -k logins

# Monitor SSH config
-w /etc/ssh/sshd_config -p wa -k sshd

# -----------------------------------------------------------------------------
# CRITICAL FILES
# -----------------------------------------------------------------------------
# Monitor cron
-w /etc/crontab -p wa -k cron
-w /etc/cron.d/ -p wa -k cron
-w /etc/cron. daily/ -p wa -k cron
-w /etc/cron.hourly/ -p wa -k cron
-w /etc/cron.monthly/ -p wa -k cron
-w /etc/cron.weekly/ -p wa -k cron

# Monitor Docker
-w /usr/bin/docker -p wa -k docker
-w /var/lib/docker -p wa -k docker
-w /etc/docker -p wa -k docker
-w /var/run/docker.sock -p wa -k docker

# -----------------------------------------------------------------------------
# MAKE RULES IMMUTABLE (Uncomment for production)
# -----------------------------------------------------------------------------
# -e 2
AUDITEOF

# Restart auditd
systemctl enable auditd
systemctl restart auditd

log "✅ Audit logging configured"

# -----------------------------------------------------------------------------
# STAGE 8: ROOTKIT DETECTION
# -----------------------------------------------------------------------------
header "🔍 STAGE 8: Rootkit Detection Setup"

log "Configuring rootkit detection..."

# Update rkhunter database
rkhunter --update || true
rkhunter --propupd

# Configure rkhunter for cron
cat > /etc/default/rkhunter << 'RKHUNTEREOF'
CRON_DAILY_RUN="yes"
CRON_DB_UPDATE="yes"
APT_AUTOGEN="yes"
RKHUNTEREOF

# Initial chkrootkit scan (background)
log "Running initial rootkit scan (background)..."
nohup chkrootkit > /var/log/chkrootkit-initial.log 2>&1 &

log "✅ Rootkit detection configured"

# -----------------------------------------------------------------------------
# STAGE 9: FILE INTEGRITY MONITORING
# -----------------------------------------------------------------------------
header "📂 STAGE 9: File Integrity Monitoring (AIDE)"

log "Initializing AIDE database..."

# Configure AIDE
cat > /etc/aide/aide.conf.d/99_custom << 'AIDEEOF'
# Custom AIDE rules
/etc/passwd$ f ConfFiles
/etc/shadow$ f ConfFiles
/etc/group$ f ConfFiles
/etc/gshadow$ f ConfFiles
/etc/ssh$ d ConfFiles
/etc/nginx$ d ConfFiles
AIDEEOF

# Initialize AIDE database (takes a while)
log "Initializing AIDE database (this may take several minutes)..."
aideinit -y -f || true

log "✅ File integrity monitoring configured"

# -----------------------------------------------------------------------------
# STAGE 10: SECURE SHARED MEMORY
# -----------------------------------------------------------------------------
header "💾 STAGE 10: Secure Shared Memory"

log "Securing shared memory..."

# Add to fstab if not exists
if ! grep -q "tmpfs /run/shm" /etc/fstab; then
    echo "tmpfs /run/shm tmpfs defaults,noexec,nosuid 0 0" >> /etc/fstab
fi

log "✅ Shared memory secured"

# -----------------------------------------------------------------------------
# STAGE 11: DISABLE UNNECESSARY SERVICES
# -----------------------------------------------------------------------------
header "🔌 STAGE 11: Disable Unnecessary Services"

log "Disabling unnecessary services..."

SERVICES_TO_DISABLE=(
    "bluetooth"
    "cups"
    "avahi-daemon"
    "ModemManager"
)

for service in "${SERVICES_TO_DISABLE[@]}"; do
    if systemctl is-enabled "$service" 2>/dev/null; then
        systemctl disable "$service" 2>/dev/null || true
        systemctl stop "$service" 2>/dev/null || true
        log "Disabled:  $service"
    fi
done

log "✅ Unnecessary services disabled"

# -----------------------------------------------------------------------------
# STAGE 12: LOG ROTATION
# -----------------------------------------------------------------------------
header "📋 STAGE 12: Log Rotation Configuration"

log "Configuring log rotation..."

cat > /etc/logrotate.d/security << 'LOGROTATEEOF'
# Security log rotation
/var/log/auth.log
/var/log/fail2ban.log
/var/log/audit/audit.log
{
    weekly
    rotate 12
    compress
    delaycompress
    missingok
    notifempty
    create 0640 root adm
    sharedscripts
    postrotate
        /usr/lib/rsyslog/rsyslog-rotate
    endscript
}

# Nginx logs
/var/log/nginx/*.log {
    daily
    rotate 14
    compress
    delaycompress
    missingok
    notifempty
    create 0640 www-data adm
    sharedscripts
    postrotate
        [ -f /var/run/nginx.pid ] && kill -USR1 `cat /var/run/nginx.pid`
    endscript
}
LOGROTATEEOF

log "✅ Log rotation configured"

# -----------------------------------------------------------------------------
# FINAL SUMMARY
# -----------------------------------------------------------------------------
header "🎉 SECURITY HARDENING COMPLETE"

echo "" | tee -a "$LOG_FILE"
echo "═══════════════════════════════════════════════════════════════" | tee -a "$LOG_FILE"
echo " SECURITY HARDENING SUMMARY" | tee -a "$LOG_FILE"
echo "═══════════════════════════════════════════════════════════════" | tee -a "$LOG_FILE"
echo "" | tee -a "$LOG_FILE"
echo " ✅ SSH hardened (key-only, no root login)" | tee -a "$LOG_FILE"
echo " ✅ Firewall configured (UFW)" | tee -a "$LOG_FILE"
echo " ✅ Intrusion prevention (Fail2Ban)" | tee -a "$LOG_FILE"
echo " ✅ Automatic security updates enabled" | tee -a "$LOG_FILE"
echo " ✅ Kernel hardened (sysctl)" | tee -a "$LOG_FILE"
echo " ✅ Audit logging enabled (auditd)" | tee -a "$LOG_FILE"
echo " ✅ Rootkit detection (rkhunter, chkrootkit)" | tee -a "$LOG_FILE"
echo " ✅ File integrity monitoring (AIDE)" | tee -a "$LOG_FILE"
echo " ✅ Log rotation configured" | tee -a "$LOG_FILE"
echo "" | tee -a "$LOG_FILE"
echo "═══════════════════════════════════════════════════════════════" | tee -a "$LOG_FILE"
echo " IMPORTANT NEXT STEPS" | tee -a "$LOG_FILE"
echo "═══════════════════════════════════════════════════════════════" | tee -a "$LOG_FILE"
echo "" | tee -a "$LOG_FILE"
echo " 1. Test SSH access in a NEW terminal before disconnecting" | tee -a "$LOG_FILE"
echo " 2. Review firewall rules:  sudo ufw status" | tee -a "$LOG_FILE"
echo " 3. Check Fail2Ban status: sudo fail2ban-client status" | tee -a "$LOG_FILE"
echo " 4. Review audit logs: sudo ausearch -i" | tee -a "$LOG_FILE"
echo " 5. Run security audit: sudo bash security-audit.sh" | tee -a "$LOG_FILE"
echo "" | tee -a "$LOG_FILE"
echo " Backup location: $BACKUP_DIR" | tee -a "$LOG_FILE"
echo " Log file: $LOG_FILE" | tee -a "$LOG_FILE"
echo "" | tee -a "$LOG_FILE"
echo "═══════════════════════════════════════════════════════════════" | tee -a "$LOG_FILE"